
/* tabla medicos */
INSERT INTO medicos (id, nombre, apellido, documento_identidad, profesion, telefono, email) VALUES(1, 'Ricardo', 'Gutierrez', '24300401', 'Medico general', '3122020', 'ricardo@gmail.com');
INSERT INTO medicos (id, nombre, apellido, documento_identidad, profesion, telefono, email) VALUES(2, 'Joaquin', 'Ruiz', '24300402', 'Medico general', '3122020', 'ricardo@gmail.com');
INSERT INTO medicos (id, nombre, apellido, documento_identidad, profesion, telefono, email) VALUES(3, 'Jose', 'Gutierrez', '24300403', 'Medico general', '3122020', 'ricardo@gmail.com');
INSERT INTO medicos (id, nombre, apellido, documento_identidad, profesion, telefono, email) VALUES(4, 'Monica', 'Ramirez', '24300404', 'Psicologa', '3122060', 'Monica@gmail.com');
INSERT INTO medicos (id, nombre, apellido, documento_identidad, profesion, telefono, email) VALUES(5, 'Angela', 'Muñoz', '24300405', 'Fisioterapeuta', '3122067', 'angela@gmail.com');
INSERT INTO medicos (id, nombre, apellido, documento_identidad, profesion, telefono, email) VALUES(6, 'Sebastian', 'Velez', '24300406', 'Cardiologo', '3122012', 'sebastian@gmail.com');
INSERT INTO medicos (id, nombre, apellido, documento_identidad, profesion, telefono, email) VALUES(7, 'Juan', 'Guerra', '24300407', 'Gastroenterologo', '3122080', 'santiago@gmail.com');
INSERT INTO medicos (id, nombre, apellido, documento_identidad, profesion, telefono, email) VALUES(8, 'Santiago', 'Guerra', '24300408', 'Pediatra', '3122080', 'santiago@gmail.com');
INSERT INTO medicos (id, nombre, apellido, documento_identidad, profesion, telefono, email) VALUES(9, 'Maria', 'Guerra', '24300409', 'Odontologa', '3122080', 'santiago@gmail.com');
INSERT INTO medicos (id, nombre, apellido, documento_identidad, profesion, telefono, email) VALUES(10, 'Isabel', 'Guerra', '24300410', 'Odontologa', '3122080', 'santiago@gmail.com');

/* tabla pacientes */
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Juan', 'Botero', '1088001001', 'Masculino', 'Pereira', '2000-01-01', 'O+', 'Sura', '30 de agosto #30-10', '3122020', 'juan@gmail.com', 'Soltero');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Felix', 'Ruiz', '1088001002', 'Masculino', 'Pereira', '2004-01-01', 'O+', 'Nueva', '30 de agosto #30-23', '3122054', 'felix@gmail.com', 'Casado');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Maria', 'Ramirez', '1088001003', 'Femenino', 'Manizales', '2001-01-01', '0-', 'Saludcoop', '30 de agosto #30-67', '3122078', 'maria@gmail.com', 'Soltera');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Ivan', 'Gomez', '1088001004', 'Masculino', 'Cucuta', '1989-01-01', 'A+', 'Sura', '30 de agosto #30-56', '3122050', 'ivan@gmail.com', 'Viudo');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Jose', 'Galindo', '1088001005', 'Masculino', 'Pereira', '1992-01-01', 'A-', 'Colsanitas', '30 de agosto #30-34', '3122098', 'jose@gmail.com', 'Soltero');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Aleja', 'Botero', '1088001006', 'Femenino', 'Pereira', '2000-01-01', 'O+', 'Nueva', '30 de agosto #30-10', '3122020', 'aleja@gmail.com', 'Soltera');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Juan', 'Vargas', '1088001007', 'Masculino', 'Pereira', '2000-01-01', 'O+', 'Sura', '30 de agosto #30-10', '3122020', 'juan1@gmail.com', 'Soltero');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Pepe', 'Morales', '1088001008', 'Masculino', 'Manizales', '2000-01-01', 'A+', 'Sura', '30 de agosto #30-10', '3122020', 'Pepe@gmail.com', 'Soltero');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Alicia', 'Botero', '1088001009', 'Femenino', 'Pereira', '2000-01-01', 'A-', 'Sura', '30 de agosto #30-10', '3122020', 'alicia@gmail.com', 'Soltera');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Ruben', 'Botero', '1088001010', 'Masculino', 'Pereira', '2000-01-01', 'O+', 'Sura', '30 de agosto #30-10', '3122020', 'ruben@gmail.com', 'Soltero');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Lina', 'Botero', '1088001011', 'Femenino', 'Pereira', '2000-01-01', 'O+', 'Sura', '30 de agosto #30-10', '3122020', 'lina@gmail.com', 'Soltera');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Popeye', 'Botero', '1088001012', 'Masculino', 'Pereira', '2000-01-01', 'O+', 'Sura', '30 de agosto #30-10', '3122020', 'popeye@gmail.com', 'Casado');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Pepe', 'Botero', '1088001013', 'Masculino', 'Pereira', '2000-01-01', 'O+', 'Sura', '30 de agosto #30-10', '3122020', 'popeye@gmail.com', 'Casado');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Ruben', 'Botero', '1088001014', 'Masculino', 'Pereira', '2000-01-01', 'O+', 'Sura', '30 de agosto #30-10', '3122020', 'popeye@gmail.com', 'Casado');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Maggie', 'Botero', '1088001015', 'Femenino', 'Pereira', '2000-01-01', 'O+', 'Sura', '30 de agosto #30-10', '3122020', 'popeye@gmail.com', 'Soltera');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Laura', 'Botero', '1088001016', 'Femenino', 'Pereira', '2000-01-01', 'O+', 'Sura', '30 de agosto #30-10', '3122020', 'popeye@gmail.com', 'Soltera');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Maria', 'Botero', '1088001017', 'Femenino', 'Pereira', '2000-01-01', 'O+', 'Sura', '30 de agosto #30-10', '3122020', 'popeye@gmail.com', 'Soltera');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Jorge', 'Botero', '1088001018', 'Masculino', 'Pereira', '2000-01-01', 'O+', 'Sura', '30 de agosto #30-10', '3122020', 'popeye@gmail.com', 'Casado');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Paula', 'Botero', '1088001019', 'Femenino', 'Pereira', '2000-01-01', 'O+', 'Sura', '30 de agosto #30-10', '3122020', 'popeye@gmail.com', 'Soltera');
INSERT INTO pacientes (nombre, apellido, documento_identidad, genero, lugar_nacimiento, fecha_nacimiento, tipo_sangre, eps, direccion, telefono, email, estado_civil) VALUES('Jose', 'Botero', '1088001020', 'Masculino', 'Pereira', '2000-01-01', 'O+', 'Sura', '30 de agosto #30-10', '3122020', 'popeye@gmail.com', 'Casado');


/* tabla consultas */
INSERT INTO consultas (medico_id, motivo_consulta, alergias,patologias, patologias_familiares, medicamento, diagnostico, tratamiento, paciente_id, created_at) VALUES(1, 'Malestar general', 'Ninguna', 'Ninguna', 'Diabetes', 'Ninguno', 'Gripa', 'Acetaminofen', 1, '2021-02-13');
INSERT INTO consultas (medico_id, motivo_consulta, alergias,patologias, patologias_familiares, medicamento, diagnostico, tratamiento, paciente_id, created_at) VALUES(5, 'Dolor abdominal', 'Ninguna', 'Ninguna', 'Diabetes', 'Ninguno', 'Gastroenteritis', 'Ozomeprazol', 1, '2021-06-23');
INSERT INTO consultas (medico_id, motivo_consulta, alergias,patologias, patologias_familiares, medicamento, diagnostico, tratamiento, paciente_id, created_at) VALUES(4, 'Dolor de cabeza', 'Piña, fresa, cerdo', 'Ninguna', 'Cancer', 'Advil', 'Migraña', 'Acetaminofen, Advil forte', 2, '2021-04-10');
INSERT INTO consultas (medico_id, motivo_consulta, alergias,patologias, patologias_familiares, medicamento, diagnostico, tratamiento, paciente_id, created_at) VALUES(5, 'Diarrea', 'Ninguna', 'Gastritis cronica', 'Ninguna', 'Ninguno', 'Bacterias y amibas', 'Fuluzal', 3, '2021-09-20');
INSERT INTO consultas (medico_id, motivo_consulta, alergias,patologias, patologias_familiares, medicamento, diagnostico, tratamiento, paciente_id, created_at) VALUES(6, 'Malestar general', 'Ninguna', 'Ninguna', 'Diabetes', 'Ninguno', 'Gripa', 'Acetaminofen', 2, '2021-02-13');
INSERT INTO consultas (medico_id, motivo_consulta, alergias,patologias, patologias_familiares, medicamento, diagnostico, tratamiento, paciente_id, created_at) VALUES(7, 'Malestar general', 'Ninguna', 'Ninguna', 'Diabetes', 'Ninguno', 'Gripa', 'Acetaminofen', 4, '2021-02-13');
INSERT INTO consultas (medico_id, motivo_consulta, alergias,patologias, patologias_familiares, medicamento, diagnostico, tratamiento, paciente_id, created_at) VALUES(8, 'Malestar general', 'Ninguna', 'Ninguna', 'Diabetes', 'Ninguno', 'Gripa', 'Acetaminofen', 5, '2021-02-13');
INSERT INTO consultas (medico_id, motivo_consulta, alergias,patologias, patologias_familiares, medicamento, diagnostico, tratamiento, paciente_id, created_at) VALUES(9, 'Dolor en la encia', 'Ninguna', 'Ninguna', 'Diabetes', 'Ninguno', 'Sensibilidad', 'Acetaminofen', 6, '2021-02-13');
INSERT INTO consultas (medico_id, motivo_consulta, alergias,patologias, patologias_familiares, medicamento, diagnostico, tratamiento, paciente_id, created_at) VALUES(10, 'Dolor en la encia', 'Ninguna', 'Ninguna', 'Diabetes', 'Ninguno', 'Sensibilidad', 'Acetaminofen', 7, '2021-02-13');
